### PR TITLE
Made code more glamorous

### PR DESCRIPTION
**Pull request by trickybestia**
Made code more glamorous lol.

### CODE REVIEW

**Review by TypicalIllusion — COMMENTED** [review]
As this plugin was made 3-5 times, I'm just doing this so I can say I made a plugin by myself.
I'll remember these changes for my next plugin though

**Comment by trickybestia** [comment]
Ok, closedsource boi

**Comment by TypicalIllusion** [comment]
I'll put it in a different branch ig

**Comment by TypicalIllusion** [comment]
When I'm not busy

**Review by TypicalIllusion — CHANGES_REQUESTED** [review]
make it on your branch

**Comment by An4r3w** [comment]
**no**

**Comment by trickybestia** [comment]
I think I'm so lazy to do it :c

**Pull request closed without merging**
