### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by PintTheDragon**
Improves the formatting and removes redundant code.

### CODE REVIEW

**Comment by TypicalIllusion** [comment]
i like to do things myself *pint*

**Comment by TypicalIllusion** [comment]
most of the time atleast ~~this is my first time~~

**Comment by Kade-github** [comment]
thats not how open source works. might as well be closed source tbh

**Comment by TypicalIllusion** [comment]
It changes a lot of things and makes it pretty much not my plugin

**Comment by TypicalIllusion** [comment]
It changed the whole player.cs file

**Comment by Thundermaker300** [comment]
The point of Exiled plugins being open source is to allow anyone to contribute. Pint spent his time to make your code *better*, that's not a valid reason to close it just because you want to do it yourself.

**Comment by TypicalIllusion** [comment]
yes, but then im going to ask what {X} means and get told to learn c#, its not worth being bothered about that.

**Comment by TypicalIllusion** [comment]
another reason this is open source is so i can link people it. im in school and cant do that

**Comment by Kade-github** [comment]
> another reason this is open source is so i can link people it. im in school and cant do that

Open-source software is a type of computer software in which source code is released under a license in which the copyright holder grants users the rights to use, study, change, and distribute the software to anyone and for any purpose. **Open-source software may be developed in a collaborative public manner.**

What you are doing, is saying "I'm not making my plugin better because it'll make it look like it's not mine anymore!" which is really selfish. Pint spent time trying to improve your plugin, and you throw it away because "it's not mine anymore."

**Comment by TypicalIllusion** [comment]
i dont even understand it as much as my version

i'd prefer to do things my way and understand it

**Comment by TypicalIllusion** [comment]
and yes, i do appreciate pint for doing this.
no, i dont have to use it.

Im not trying to sound selfish at all, im just saying i prefer it my way because i understand what im doing.

**Pull request closed without merging**
